### ISSUE TITLE
Only question (no issue)

### ISSUE THREAD

**Issue by AppWerft** [TheSmiths-Widgets/ts.videoprovider#1]
How I can reference files like in your lib folder?

Awesoem work -- I have successful tested. I hope it runs a couple of time.

**Comment by manumaticx** [comment]
These are [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules). (see [`.gitmodules`](https://github.com/TheSmiths-Widgets/ts.videoprovider/blob/master/.gitmodules) )

**Comment by KtorZ** [comment]
Indeed @manumaticx , Thanks for the reply. 
If you want to use lib files used in that module (which are also modules) in a different context, you can either import a submodule and directly require the uncompressed corresponding js file or seemingly import them as commonJS modules as every other commonJS module. 

By the by @AppWerft , I appreciate :).

**Comment by AppWerft** [comment]
more question: I don't see package.json.

**Comment by KtorZ** [comment]
And you're seeing right. 
I have to bring all modules to `npm` nevertheless, I am very busy at the current moment. This will be done during October. 
So far, I only rely on `git` and `gittio` to install modules. As they are supposed to live in a Titanium context, you can simply clone the repository and drop the built zip file in your Ti project. 

`npm` is coming soon :)

**Comment by AppWerft** [comment]
@manumaticx Thanks for you hint. I have learned.  Here my result: https://github.com/AppWerft/Ti.YoutubeProxy
If I try to start titaniumifier then the libs are not found.

```
Error: Cannot find module './lib/ts.httprequest' from '/Users/fuerst/Documents/Appcelerator_Studio_Workspace/Ti.YoutubeProxy'
```

I can see the modules on my mac. I think some entries in package.json are missing

**Comment by KtorZ** [comment]
Try this `require('./lib/ts.httprequest/ts.httprequest')`

or just, import the zipfile into your root folder, add the module in your tiapp.xml and simply write:

`require('ts.httprequest')`;

**Comment by AppWerft** [comment]
Merci Bien, I want avoid copying. And now I used your syntax.

```
var HTTPRequest = require('./lib/ts.httprequest/ts.httprequest');
var VideoProvider = require('./lib/ts.videoprovider/ts.videoprovider');
var Promise = require('./lib/org.favo.promise');
```

I'm wondering: now 

```
Error: Cannot find module './lib/ts.cryptojs256/ts.cryptojs256.js' from '/Users/fuerst/Documents/Appcelerator_Studio_Workspace/Ti.YoutubeProxy/lib/ts.videoprovider'
```

The system doesn't work recursive …

**Comment by TravisTheSmiths** [comment]
It's supposed to be. Make sure your submodules are initialized as well as
their own submodules.

Also, again, I'll migrate to npm soon and take advantage of the package
management system. For now, please use the built version of each module and
require them as commonJS modules to avoid any trouble.
